### ISSUE TITLE
stable/mongodb-replicaset: no such file or directory

### ISSUE THREAD

**Issue by montyz** [maorfr/helm-inject#1]
This command works as I expect:

``` 
$ helm upgrade -f /home/jovyan/specs/nodebuckets/mongo-helm-nodebuckets.yaml nodebuckets stable/mongodb-replicaset
Release "nodebuckets" has been upgraded. Happy Helming!
LAST DEPLOYED: Mon Oct  1 18:21:35 2018
...
```

However when I try to use `inject` it fails with this message:

```
$ helm inject upgrade --namespace nodebuckets -f /home/jovyan/specs/nodebuckets/mongo-helm-nodebuckets.yaml nodebuckets stable/mongodb-replicaset
lstat stable/mongodb-replicaset: no such file or directory
```

I don't understand what is wrong.

**Comment by alexandrevilain** [comment]
I've got the same issue using the `stable/traefik` chart.
It looks that the issue is related to charts installed from repositories.

**Comment by maorfr** [comment]
Hi @montyz @alexandrevilain,
thanks for bringing up this issue.

Can you give it another try now? I`ve added a new release which fixes this issue.

**Comment by alexandrevilain** [comment]
Hi! 
Thanks! I'll give it a try!
