### ISSUE TITLE
There should be a way to pass flags to the injector

### ISSUE THREAD

**Issue by robbert229** [maorfr/helm-inject#2]
So far I haven't found a way of passing flags to the injector, which I think would be a really nice feature to have. For example, what about passing flags to the linkerd injector s.t. you can enable optional tls? Currently to my understanding this isn't possible.

**Comment by maorfr** [comment]
You are right :)

https://github.com/maorfr/helm-inject/blob/master/README.md#notes

Flags for linkerd can be added. You can write here which flags, and I can add them.

You can also choose to get involved and try to tackle this yourself ;)

Let me know!

**Comment by maorfr** [comment]
You are right!
Added the `--inject-flags` in version 0.1.8.
uninstall and reinstall and you should be set ;)

Let me know how that works out for you.
I'll close this issue, but feel free to reopen!
