### ISSUE TITLE
LICENSE.txt references "Helm Logs Plugin" instead of "Helm Inject Plugin"

### ISSUE THREAD

**Issue by AlbinoDrought** [maorfr/helm-inject#4]
> Helm Logs Plugin
> Copyright (C) 2016, Maor Friedman

https://github.com/maorfr/helm-inject/blob/bc0893e4c457a8c6367b7dbd9fdb860fb2b1c462/LICENSE.txt

**Comment by maorfr** [comment]
Copy pasta :man_facepalming: 

Want to send a PR?
